### ISSUE TITLE
only one slide scroll on scrolling fastly

### ISSUE THREAD

**Issue by farshidshahmoradi1996** [davidcetinkaya/embla-carousel#147] opened 2021-02-28 11:22 UTC
Hi there,
how to only one slide scroll on scrolling fastly ?

**Comment by davidcetinkaya** [comment] 2021-02-28 11:32
Hi Farshid (@farshidshahmoradi1996),

Please provide more information or a link to an example of what you want to achieve. I don't understand the question.

Thank you,
David

**Comment by farshidshahmoradi1996** [comment] 2021-02-28 11:40
> Hi Farshid (@farshidshahmoradi1996),
> 
> Please provide more information or a link to an example of what you want to achieve. I don't understand the question.
> 
> Thank you,
> David

Hi David , thanks
first please see react-elastic-carousel example [here](https://sag1v.github.io/react-elastic-carousel/)  and drag items very fastly .
its not matter to your dragging speed , and how many you drag items fast carousel scroll one item.
but in this awesome embla-carousel when you drag items fast many slides scroll happean . 
how to prevent this ?

**Comment by davidcetinkaya** [comment] 2021-02-28 11:54
Hi again Farshid (@farshidshahmoradi1996),

Thank you for the details and the link. This issue has been raised before here #38. At the time of writing this isn't possible. If you want to know why, please read [this comment](https://github.com/davidcetinkaya/embla-carousel/issues/38#issuecomment-565814315).

I'm closing this as a duplicate. If you want to discuss this further, you're welcome to do so in issue #38.

Best,
David

**Closed by davidcetinkaya** 2021-02-28 11:54 UTC

**Comment by davidcetinkaya** [comment] 2021-03-30 12:39
Duplicate of #38.
