### ISSUE TITLE
Keeping end/start of loop carousel items visible until dragEnd

### ISSUE THREAD

**Issue by iamkevingreen** [davidcetinkaya/embla-carousel#118] opened 2020-11-17 18:32 UTC
Hey David,

Huge fan of the carousel 👍 . I've got an interesting feature request, that if you have insight into how I could do without rolling into the core would love some eyes on it:

https://jx628.csb.app/

What I would want the expected behavior to be is that the slideshow either: 
1. clones a first/last item to the end of the chair (I feel like other slideshows do this, don't believe it's necessary and over complicates)
2. the slide to the left/right of the visible end of loop is not moved until after dragEnd. 

Using the example above I put a border around the visible container, and you can see as you drag the active item left or right that the next/prev slide sort of pops out of frame. I know that your more standard implementation has an `overflow:hidden` wrap. But I often encounter slideshows where the design lends itself to seeing the next/prev slide on the edge of the slideshow so I created that effect to the best of my understanding of the embla world. Perhaps this isn't something that is `core` but wondering if there is another way I can basically delay the `left: 0` that occurs as you drag an item in and out of the frame.

**Comment by davidcetinkaya** [comment] 2020-11-17 19:43
Hello Kevin (@iamkevingreen),

> But I often encounter slideshows where the design lends itself to seeing the next/prev slide on the edge of the slideshow...

**Embla allows for this** and the Embla loop engine is actually more exact than the Flickity one. The issue in your example is caused by the horizontal auto margin applied to the container, because you have `max-width: 800px;` applied to it.

If you resize your window to anything smaller than 800px, it should work as expected right? It works because the margin is gone. So what's happening is that the margin areas are added as additional space to the lending area which leaves the loop effect exposed.

<img width="500" alt="screen" src="https://user-images.githubusercontent.com/11529148/99436779-c61e7600-2911-11eb-8516-1da4e9d5a2a0.png">

The solution to this is that the Embla container has to be full width. You basically have to remove the `max-width: 800px;` from the Embla container, and apply a max width directly to the slides instead. In your example your slide widths are 80% of a 800px container, so each slide should then have a max width of 800px * 0.8 = **640px**. Here's a [CodeSandbox](https://codesandbox.io/s/elastic-lovelace-9lnm1) demonstrating how to achieve this.

Here are two screenshots showing the container size (the red line) before and after applying the suggested fix in the [CodeSandbox](https://codesandbox.io/s/elastic-lovelace-9lnm1):

### Before 
<img width="500" alt="before" src="https://user-images.githubusercontent.com/11529148/99438846-ad638f80-2914-11eb-9dbe-25c34c6648cb.png">

### After
<img width="500" alt="after" src="https://user-images.githubusercontent.com/11529148/99438851-afc5e980-2914-11eb-8057-cb0ec3d04472.png">

Note that you can change slide sizes in your CSS with media queries if you prefer a percentage value over pixels. Embla will pick that up when you resize the window.

Let me know if it helps.
David

**Comment by iamkevingreen** [comment] 2020-11-17 21:27
I see what's happening, this was super helpful. I was essentially trying to create the layout before creating the slideshow, when I should have created the layout from the slideshow itself. I am tweaking the use case on my side with these suggestions and think it's coming out nicely now!

The responsiveness (max 800px) was simply a test to where I was in the process, the actual mobile->desktop will be a little different but I think  this resolved everything on my end.

The solution here seems to be make the slideshow more or less full width and let the inner slides size the experience. 

Cheers.

**Comment by davidcetinkaya** [comment] 2020-11-18 04:44
Hello again Kevin (@iamkevingreen),

I’m glad my explanation made sense 🙂. Nice to hear that you got it sorted. I’m closing this issue as resolved then?

Best,
David

**Closed by davidcetinkaya** 2020-11-18 04:44 UTC
Labels: demonstration, done
