### ISSUE TITLE
Unable to access and move through carousels with the keyboard.

### ISSUE THREAD

**Issue by didier** [davidcetinkaya/embla-carousel#278] opened 2022-02-04 00:54 UTC
### Feature request is related to

- [x] embla-carousel (core package)
- [x] embla-carousel-react
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-docs (documentation website)

### Is your feature request related to an issue?

I'm unable to focus on or navigate the carousel with my keyboard.

### Describe the solution you'd like

For accessibility reasons, I would expect interactive elements to be interactive with a keyboard as well as a mouse.

### Describe alternatives you've considered

There really isn't an alternative to this, aside from not supporting it at all.

### Additional context

n.a.

**Comment by davidcetinkaya** [comment] 2022-02-05 21:10
Hi @didier,

As of **v6**, Embla Carousel accepts [plugins](https://www.embla-carousel.com/api/plugins/). Feel free to create a plugin called `embla-carousel-keyboard-nav` if you want. I can provide some guidance to get you started.

Two friendly reminders:

1. Please respect my [decision here](https://github.com/davidcetinkaya/embla-carousel/issues/187#issue-873669552).
2. This issue is a **duplicate**, and this has been requested before in issue #53. Further discussions continue there. Please search existing issues before creating a new issue.

Kindly,
David

**Comment by davidcetinkaya** [comment] 2022-02-05 21:10
Duplicate of #53.

**Closed by davidcetinkaya** 2022-02-05 21:10 UTC
Labels: feature request

**Comment by dathmart** [comment] 2022-03-20 17:42
@didier I was having issues with keyboard navigation as well before I found [this issue thread](https://github.com/davidcetinkaya/embla-carousel/issues/239#issuecomment-1073295022). This should allow your carousel to be navigated using Tab( + Shift).

**Comment by davidcetinkaya** [comment] 2022-03-21 07:15
@dathmart thanks for the update. Although they’re similar, I guess this feature request is more about using the left/right arrow keys to scroll to the previous/next slide, rather than tab accessibility. It might be worth noting that the tab accessibility code works for slides with tab index set or with focusable children inside. Thanks for sharing the update though! It might help others looking for the tab accessibility feature 🙂.
