### ISSUE TITLE
Snappoints on showing multiple slides

### ISSUE THREAD

**Issue by mrksmts** [davidcetinkaya/embla-carousel#19] opened 2019-08-09 09:13 UTC
Currently I am implementing Embla Carousel in a project where we have multiple slides in the viewport at once, this basically means 2.5 slides are always visible.

When we containScroll and align start the items the snappoints for slide 4 and 5 are the same so it feels there should be one less snappoint for these settings.

I've setup a sandbox forked from one of the other issues to explain this issue: https://codesandbox.io/s/embla-carousel-loop-false-xdpsb?fontsize=14

**Comment by davidcetinkaya** [comment] 2019-08-09 15:31
Hello Mark (@mrksmts),

Thank you for taking the time to report this issue + the clear sandbox example 👍🏻.
I hope you don’t mind the delayed response, I have a newborn at home 👶🏻🍼.

Have you tried setting the `slidesToScroll` option to `2`? When you have 2 fully visible slides in viewport you can cut redundant snap points using this option.

I’d very much appreciate if you can confirm if this is the functionality you’re looking for.

All the best!
David

**Comment by mrksmts** [comment] 2019-08-12 11:55
Hi David (@davidcetinkaya)

I am not sure that would work because we would like to be able to slide per item.

And in the example the slide width is 40% so it would always be 2 but If you make it 250px for example and the carousel 100% it really depends on the width of the carousel and the amount of slides in the view that would determine the snap points.

Best, 

Mark

**Comment by davidcetinkaya** [comment] 2019-08-12 12:14
Hi Mark (@mrksmts),

I understand your point of view. In the example you provided slide 4 and 5 share the same snap point because of `containScroll` that cuts excessive scroll at the end.

I don’t know what a sensible solution to this would look like. The current implementation of `containScroll` is by design, and works pretty much like [Flickity’s contain](https://flickity.metafizzy.co/options.html#contain). Implicitly cutting snap points could lead to confusion when using options like `slidesToScroll`.

Maybe we should consider a new option. What do **you** think?

**Comment by mrksmts** [comment] 2019-08-14 08:56
Hi David (@davidcetinkaya)

What do you think about something like a boolean called `trimSnapPositions` which basically removes all snap points that are the same? Then you could leave it up to the user.

**Comment by davidcetinkaya** [comment] 2019-08-14 12:48
Hi again Mark (@mrksmts),

Thanks for getting back to me. Let me try this in code and see if it’s an easy fix or if there are some unexpected consequences with this 🧐.

I’ll get to it as soon as possible, I have a newborn getting my primary attention at home so thank you for being patient 👶🏻🍼.

Best,
David

**Comment by SachaMPS** [comment] 2019-08-14 13:54
Wanted to ask the exact same thing and found this open issue right now.. made more or less the same example... https://codepen.io/sachamps/pen/XWrXvGq

If you could point me to the best place in your code to get a hand on it i would at least try to make a PR which you could review... If not no problem... Congratulations 👶🏻!!!

**Comment by davidcetinkaya** [comment] 2019-08-14 14:28
Welcome Sacha (@SachaMPS),

Thank you 👶🏻.

And another good example illustrating the feature request clearly 👍🏻.

What’s **your** opinion on this?

1. Snap points that share the same position and don’t trigger any scroll should be merged.
2. It should be an option for the user.

❓

Thank you in advance,
David

**Comment by SachaMPS** [comment] 2019-08-14 14:52
HeyHo @davidcetinkaya,

i am just reading (and logging :) through your code to find out how all the stuff works.

Right now I would try not to mess with the anything too much at all. I am asking myself if the API call `canScrollNext` in that case should return `false`. 

Alternatively there could be another API call which exposes `reachedMin`.

In both cases there wouldn't be the need to add something via UserOptions...

**Comment by davidcetinkaya** [comment] 2019-08-14 15:56
Hi Sacha (@SachaMPS),

We could make `canScrollPrev` and `canScrollNext` recognize when the carousel is scollable or not, but that doesn't solve the problem with **dot navigation**.

**Example:**
Let's say we have a carousel setup with the following:

- 5 slides
- containScroll: true
- align: 'start'

👉 See [CodeSandbox](https://xdpsb.csb.app)

In order to setup **dot navigation** there's a useful API method `scrollSnapList()`. In the example above, `scrollSnapList()` will return 5 snap points. However, only 3 of them will trigger an actual scroll. So when we've reached slide `3`, the next button won't do anything/scroll further. Now if the **dot navigation** shows `5` dots it could be confusing for the user:

![embla](https://user-images.githubusercontent.com/11529148/63036053-a1d91b80-bebc-11e9-96fa-cf4a2445bb96.png)

We need to solve this too...

**Comment by SachaMPS** [comment] 2019-08-14 16:36
@davidcetinkaya  I am not sure if a dot navigation makes sense in that kind of config at all... I mean what does the Dot-Navigation mean in that case... I think having 5 slides  but only three dotes to navigate with would be totally irritating.

**Comment by davidcetinkaya** [comment] 2019-08-14 18:52
@SachaMPS, it’s not obvious to me that the number of slides has to match the number of dots. In a real world usage example carousels generally don’t have obvious slide numbers like in the example I sent you. They often contain images or maybe a combination of text and an image.

If slide widths are small enough so 2 or more slides are visible in viewport at the same time, it might be equally annoying for the user to scroll by each slide one at a time. Therefore there is a slidesToScroll option available which is a feature many Carousel plugins have. Take a look here:

👉🏻 [CodeSandbox](https://1g4rk.csb.app)

That’s why I think we should consider merging excessive snap points that don’t trigger any scroll. But as you can see in the discussion above, I’d be happy if we can find a good solution for this.

**Comment by davidcetinkaya** [comment] 2019-08-19 12:11
Hi Mark (@mrksmts),

Just want to let you know that I'm working on this. I've not decided if:

**A.** Snap points that don’t trigger any scroll will be merged automatically.
**B.** It should be an option for the user.

But at this point I've tried this in code (in an ugly way) and I'm hoping to get some time to finish this and wrap it up soon.

Best,
David

**Comment by mrksmts** [comment] 2019-08-20 08:36
Hi David (@davidcetinkaya)

Thanks! That's great to hear. You could put it in by default and give the user the option to turn it off or the other way around.

Let me know if I can test or help with anything.


Best,
Mark

**Comment by davidcetinkaya** [comment] 2019-08-22 15:02
Hello Mark (@mrksmts),

No worries 👍. I have some small fixes left to do at this point. If I create a **new branch**, would you mind cloning the repo to your local machine and testing the new feature as soon as I'm finished?

Best,
David

**Comment by davidcetinkaya** [comment] 2019-08-30 19:21
Hi Mark (@mrksmts),

I'm very happy to announce that release [v2.4.0](https://github.com/davidcetinkaya/embla-carousel/releases/tag/v2.4.0) comes with the functionality you're looking for 🚀.

I decided to go with Embla **automatically merging** excessive **snap points** that share the same position, rather than making it an option. The reason being is that I couldn't think of any use case where it makes sense to have navigation that triggers no scroll at all.

Maybe some users will beat me up about this and if they do, I'd be happy to discuss this further and consider adding the old `containScroll` behaviour as a specific **option**.

I'd very much appreciate if you could test the new behaviour and give me feedback 👍.

**Comment by davidcetinkaya** [comment] 2019-09-10 07:21
Hello Mark (@mrksmts),
Just curious, have you had the change to try if this is working as expected yet?

Thanks!
David

**Comment by davidcetinkaya** [comment] 2019-09-15 11:41
Closing due to inactivity. Feel free to re-open this issue if you don’t think it’s working as expected.

Thanks for opening this issue and improving Embla 👌🏻!

**Closed by davidcetinkaya** 2019-09-15 11:41 UTC
Labels: awaiting feedback, feature request, implemented

**Comment by mrksmts** [comment] 2019-12-03 13:11
Hi @davidcetinkaya !

Sorry I didn't take the time get back to you earlier, seems like this works as expected! It is live and working like a charm! Thanks a lot! 


Best,

Mark

**Comment by davidcetinkaya** [comment] 2019-12-03 13:27
Hello Mark (@mrksmts),

Thank you for getting back to me, I appreciate it. And I'm glad it seems to be working as expected. Enjoy!

Kindly,
David

**Comment by davidcetinkaya** [comment] 2020-05-14 12:14
Hello Mark (@mrksmts) and Sacha (@SachaMPS),

I just wanted to let you know that I'm going to release Embla v.3 as soon as possible which will allow devs to choose between keeping redundant snap points or trimming them when using [containScroll](https://github.com/davidcetinkaya/embla-carousel#containscroll):

```javascript
const options = { containScroll: 'trimSnaps' }

// or

const options = { containScroll: 'keepSnaps' }
```

Cheers!
David
