### ISSUE TITLE
Settle event is not triggered when draggable is set to false

### ISSUE THREAD

**Issue by th-km** [davidcetinkaya/embla-carousel#110] opened 2020-10-10 12:02 UTC
**Describe the bug**
The settle event works as expected if the user only navigates with the left/right arrows. If the user tries to swipe first and uses the arrows again, the event is not triggered at all.

**To Reproduce**
https://codesandbox.io/s/embla-carousel-default-react-forked-cs8fb?file=/src/js/EmblaCarousel.js

**Additional context**
I'm doing page transitions at the end of each project/slide. It works perfectly with `draggable: true`, but I'd need to disable this feature on desktop.

**Browser**
Firefox 81.0, macOS

**Comment by davidcetinkaya** [comment] 2020-10-10 17:16
Hello Thomas (@th-km),

Thank you for taking time to create an issue with a helpful description and CodeSandbox 👍.

What happens if you update your Embla Carousel package to the **latest version** which is **4.0.5**? I think this bug is caused by the same problem that caused issue #87. The bug fix for issue #87 was released with [v4.0.3](https://github.com/davidcetinkaya/embla-carousel/releases/tag/v4.0.3).

Let me know if it helps.

Best,
David

**Comment by th-km** [comment] 2020-10-10 17:32
Hey @davidcetinkaya, indeed it works with **v4.0.5**.

I'm using v4.02 in production that would explain my bug. Thanks a lot for the quick answer!
Btw the v4 with the hooks is awesome 👍

**Comment by davidcetinkaya** [comment] 2020-10-10 17:36
Hello again Thomas (@th-km),

I'm happy to hear that it's working as expected 🙂.

Thanks for the feedback on the refactored hook! The old implementation had some issues and I think v4 solved them and made it much more React friendly. Much of the credit goes to @xiel 🎉.

So I'm closing this issue then?

Kindly,
David

**Comment by th-km** [comment] 2020-10-10 17:38
It works like a charm with React for sure. You can close the issue 👍

**Comment by davidcetinkaya** [comment] 2020-10-10 17:39
Enjoy 🙂!

**Closed** 2020-10-10 17:38 UTC
Labels: awaiting response
