### ISSUE TITLE
Is there any way to change slide animation?

### ISSUE THREAD

**Issue by faizanarif196** [davidcetinkaya/embla-carousel#250] opened 2021-12-05 08:14 UTC
Hi there, Embla carousel is super carousel. I am finding any way to change slide animation. Because in my last project, my buyer tell me to change slide animation. In my project I use two carousel. I have set Fade animation in one carousel. And other carousel should animated to smooth slide like keen slider. But I am using embla carousel.

is there any way or have to this features?

**Comment by davidcetinkaya** [comment] 2021-12-05 09:31
Hi @faizanarif196,

I’m not quite sure what you want to achieve? If you browse the carousels on the [examples page](https://www.embla-carousel.com/examples/basic/), they all slide smoothly. Why do you think keen-slider slides smoothly but not Embla Carousel? It doesn’t make sense to me.

Best
David

**Comment by faizanarif196** [comment] 2021-12-05 09:53
But Fade animation?

**Comment by davidcetinkaya** [comment] 2021-12-05 10:08
@faizanarif196, this has been brought up many times before. The original issue is:

- #39. 
 
Please check the **CodeSandbox** out in [this comment](https://github.com/davidcetinkaya/embla-carousel/issues/39#issuecomment-568881867).

Another thing to pay attention to is that a Fade plugin will be created soon as mentioned in this issue:

- #237

**Comment by siamahnaf198** [comment] 2021-12-05 11:42
Sorry @davidcetinkaya. 🤣 . And thank you very much. You are very helpful person. You help me with another issue some days ago.

**Comment by davidcetinkaya** [comment] 2021-12-05 13:03
Duplicate of #39.

**Closed by davidcetinkaya** 2021-12-05 13:03 UTC
Labels: feature request

**Comment by DaniAcu** [comment] 2024-12-14 18:34
Hi @davidjerleke awesome job! I'm traying to achived a bouncing effect when fit when select a slide.

Like a forcing snap every time we move next. 

Is there any way to do that?
