### ISSUE TITLE
Example How to Use Embla in a Classic HTML using the CDN in Order to Embed into Hugo

### ISSUE THREAD

**Issue by RoyiAvital** [davidcetinkaya/embla-carousel#131] opened 2020-12-15 00:11 UTC
Could you add an example which uses the CDN and is easy to embed in a regular HTML?
From there it will be easy to extrapolate this into Hugo shortcode.

Thank You.

**Comment by davidcetinkaya** [comment] 2020-12-15 13:10
Hello @RoyiAvital,

Thank you for your question. There's a bare bones example on the documentation page that demonstrates [how to use Embla with a CDN](https://davidcetinkaya.github.io/embla-carousel/#cdn-usage).

This issue is a duplicate of #32. Please take a look at the [resolution](https://github.com/davidcetinkaya/embla-carousel/issues/32#issuecomment-547003593) and let me know if it helps.

Best,
David

**Comment by davidcetinkaya** [comment] 2020-12-15 13:12
Duplicate of #32.

**Closed by davidcetinkaya** 2020-12-15 13:12 UTC

**Comment by RoyiAvital** [comment] 2020-12-15 14:44
The example on the installation page is very sparse.
Unless the user knows JS the user can't interpolate from those examples to a working example.

Any chance you convert (Add) the example with the `Arrows and Dots` and `Progress` examples into a form of CDN?

Thank You.

**Comment by davidcetinkaya** [comment] 2020-12-15 16:04
I see. Knowing your way around basic JavaScript is a requirement for using Embla Carousel, because this library is build for the web.

Basically, you'll have to go through all the `.js` files in the [CodeSandbox](https://codesandbox.io/s/embla-carousel-arrows-dots-vanilla-twh0h) and copy all the JavaScript in these files into your own JavaScript file. The same procedure should be done with the CSS. Also, don't forget the HTML markup in the example.

<img width="325" alt="files" src="https://user-images.githubusercontent.com/11529148/102239246-f2201d80-3ef6-11eb-902b-d37b5d3b9031.png">.

I hope this helps.

Best,
David

**Comment by RoyiAvital** [comment] 2020-12-15 18:21
I think it can, with some work but I guess not a lot be ,ore approachable for those who work with Static Site Generators.
Any of the examples above with full CDN based code will allow many others to embed them.
If you get such example I will create the Shortcode for Hugo for other to use it and embed it.

I have tried the approach you suggested.
The problem is your `index.js` loads a module I don't understand where to get from.
This is the reason a CDN based code will be better choice for beginners.

You can approach huge number of users with this extra example.

**Comment by davidcetinkaya** [comment] 2020-12-17 11:57
> The problem is your `index.js` loads a module I don't understand where to get from.

Which file are you referring to?

**Comment by RoyiAvital** [comment] 2020-12-17 13:30
It juts use a module load which is based on the ability of Code Sandbox's External Resources:

```
import EmblaCarousel from "embla-carousel";
```

Anyhow, If you want, I can try do my best to create easy integration to Hugo for many other to use.
But I need a simple example based on vanilla JS code (Loading `.js` files which are available on your repository / CDN).

Thank You.

**Comment by davidcetinkaya** [comment] 2020-12-18 11:44
Hi @RoyiAvital,

The **import** you mention is basically loading the script for Embla Carousel. A **CDN** setup would load the `script` like this instead:

```html
<script src="https://unpkg.com/embla-carousel@latest/embla-carousel.umd.js"></script>
```

In my first response, I mentioned the [resolution of issue 32](https://github.com/davidcetinkaya/embla-carousel/issues/32#issuecomment-547003593), which includes a link to this 👉 [CodeSandbox](https://codesandbox.io/s/embla-carousel-vanilla-github-issue-32-41mw5) that uses a CDN approach with **no imports**. The same sandbox includes an implementation of arrow and dots.

I'm curious why you're thinking that sandbox isn't sufficient?

Best,
David

**Comment by verybigelephants** [comment] 2024-08-25 15:42
i am too completely lost in the examples and don't really understand how that generator works, for example, i go here https://www.embla-carousel.com/examples/generator/, click on vanilla js and define some random properties

then it generates this https://codesandbox.io/p/sandbox/embla-carousel-generator-vanilla-lvxdp4 which is some super complicated online code editor interface and the javascripts in the file use some imports 

isn't there a simple way to use this without ESM imports in vanilla js?

but that s

**Comment by davidjerleke** [comment] 2024-08-26 06:05
@verybigelephants if you are struggling with following [this CDN guide](https://www.embla-carousel.com/get-started/cdn/) and can't get a carousel up and running, I think you rather need general JavaScript guidance rather than specific guidance with the Embla library. 

I'm not saying this to be rude but I'm the sole maintainer of this library and my spare time is very very limited. I can't also spend my spare time teaching basic JavaScript. I would advise you to join a JavaScript community on **Reddit** or **dev.to** and ask for guidance there.

**Comment by verybigelephants** [comment] 2024-08-28 09:47
@davidjerleke i did not see this example https://www.embla-carousel.com/get-started/cdn/ that's what i needed

i navigated to generated examples that were linked from the main page and it created some really confusing vscode interface

**Comment by 4teq** [comment] 2025-01-02 07:33
can i download embla files and use them in my project: not through npm. I want to import them directly in my index js among other files my app might use then webpack them out as a single bundle js file.

**Comment by jkd77** [comment] 2025-06-05 14:38
Useful tip: Using VS Code with the [Live Server extension](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer) allows launching these examples locally with minimal revisions. Once you add Live Server extension you'll have a button in the bottom right of VS Code saying "Go Live". This will launch the currently active html file into a server like: http://127.0.0.1:5500/index.html

### File revision are still necessary:

**index.html:**
1. Add links to the required CSS files as shown in the index.js import statements
`<link href="src/css/base.css" rel="stylesheet">, etc`

2. add  the type="module" attribute to the JS link at the bottom of the HTML
`<script type="module" src="src/js/index.js"></script>`

**index.js:**
1. alter the Embla import to something like: 
`import EmblaCarousel from 'https://unpkg.com/embla-carousel@8.6.0/esm/embla-carousel.esm.js';`
2. comment out the CSS imports in the index.js file
