### ISSUE TITLE
Infinite scroll calls api on every slide change

### ISSUE THREAD

**Issue by cajogit** [davidcetinkaya/embla-carousel#136] opened 2021-01-09 16:23 UTC
Hey all,

I wanted to implement infinite scroll with the carousel and followed the example. With 2 slides in view and dragFree on false it calls the api on every slide change. 

I made a codesandbox to demonstrate the issue. Check the slides array updating on top of the carousel. 

[https://codesandbox.io/s/embla-carousel-infinite-scroll-react-forked-9q01d](https://codesandbox.io/s/embla-carousel-infinite-scroll-react-forked-9q01d)

How can i solve this?

**Comment by davidcetinkaya** [comment] 2021-01-09 19:47
Hi @cajogit,

Thank you for your question. I think the strange behavior is caused by the incorrect use of `slidesToScroll` option in combination with your slide widths. Here's an explanation on how [`slidesToScroll`](https://github.com/davidcetinkaya/embla-carousel/issues/121#issuecomment-731560723) works.

If you want to display **2** slides in view with each slide 50% wide, change this in your **CSS**:

```css
.embla__slide {
  position: relative;
  min-width: 100%; /* Change this to 50% */
  padding-left: 10px;
}
```

If not, I would appreciate some more information about what you want to achieve. Thanks in advance.

Kindly,
David

**Comment by cajogit** [comment] 2021-01-09 21:23
Thanks for your quick answer.

```
.embla__slide {
  position: relative;
  min-width: 100%; /* Change this to 50% */
  padding-left: 10px;
} 
```
I had this already in my orgininal code. My bad for providing wrong informations.

My goal is to keep one part of the slide with a 16:9 ratio and one part with a fixed height. Image or video with a 16:9 ratio and under that a small div with the title.

For now i have the 16:9 ratio working like this:
```
.embla__slide__inner {
  position: relative;
  overflow: hidden;
  padding-top: 56.25%;
}
```
The padding-top is causing the strange behavior i think.

I reproduced it again on a codesandbox.
[https://codesandbox.io/s/embla-carousel-infinite-scroll-react-forked-9q01d?file=/src/css/embla.css](url)

**Comment by cajogit** [comment] 2021-01-09 22:08
d

**Comment by cajogit** [comment] 2021-01-09 22:14
Thanks for your quick answer.

```
.embla__slide {
  position: relative;
  min-width: 100%; /* Change this to 50% */
  padding-left: 10px;
} 
```
I had this already in my orginal code. My bad for providing wrong informations.

I have two components inside `embla__slide__inner`. An image and under it i have a div with text. So im not setting a height `embla__slide__inner` but this two components are setting it and everything is working great. Just this strange behavior is coming up.

**Comment by davidcetinkaya** [comment] 2021-01-10 06:44
Hi again @cajogit,

There was a bug in the Infinite Scroll example so you need to update the code in that file to the latest. I only updated the VanillaJS and forgot to update the React example. Thanks for letting me know!

Just copy paste the code from the `useInfiniteScroll.js` file in this [CodeSandbox](https://codesandbox.io/s/embla-carousel-infinite-scroll-react-z1gxc) to yours and it should work.

Let me know if it helps.

Best,
David

**Comment by cajogit** [comment] 2021-01-11 12:19
Everything is working like expected now. Thanks for the quick fix and big up for embla carousel.

**Comment by davidcetinkaya** [comment] 2021-01-11 12:32
Thanks @cajogit. Let me know if you run into more trouble. I’m closing this issue as resolved then.

Enjoy 🙂!

**Closed by davidcetinkaya** 2021-01-11 12:32 UTC
Labels: awaiting response
