### ISSUE TITLE
Is there an alternative to scrollToProgress()?

### ISSUE THREAD

**Issue by EntropyReversed** [davidcetinkaya/embla-carousel#178] opened 2021-04-13 21:15 UTC
Currently working on project that has a slider that should be moved with input. I can get progress with scrollProgress() and if I plug it into input value input is updated on Embla scroll, how can I invert it so that Embla is updated with input? scrollToProgress() and scrollBy() were good for this use case but they were deprecated in v3.0.0. Are there any alternatives?

**Comment by davidcetinkaya** [comment] 2021-04-14 08:27
Hi @EntropyReversed,

 Thank you for your question. It seems like you removed the **following part** when you created your feature request:

<img width="341" alt="options" src="https://user-images.githubusercontent.com/11529148/114674234-50270b00-9d07-11eb-91e2-b9e5e46eb717.png">

It's important to not remove this, because I don't know if I should demonstrate how to achieve what you want with VanillaJs or ReactJs. I'm going to show you how to achieve what you want with VanillaJs, and if you're using ReactJs you'll have to refactor my code into the "React way" of doing it:

### ScrollProgress extensions

```js
const createScrollProgressUtils = (embla) => {
  const withinBounds = (distance) => {
    const { target, limit } = embla.dangerouslyGetEngine()
    const { min, max, reachedMin, reachedMax } = limit
    const destination = target.get() + distance

    if (reachedMax(destination)) return max - target.get()
    if (reachedMin(destination)) return min - target.get()
    return n
  }

  const add = (progress) => {
    const { options, limit } = embla.dangerouslyGetEngine()
    const distance = limit.length * progress
    return options.loop ? distance : withinBounds(distance)
  }

  const set = (progress) => {
    const { target, scrollProgress } = embla.dangerouslyGetEngine()
    const progressToTarget = progress - scrollProgress.get(target.get())
    return withinBounds(add(progressToTarget))
  }

  return {
    scrollToProgress: (progress, snap) => {
      const { scrollBody, scrollTo } = embla.dangerouslyGetEngine()
      const distance = set(progress)
      scrollBody.useBaseMass().useBaseSpeed()
      scrollTo.distance(distance, !!snap)
    },
    scrollByProgress: (progress, snap) => {
      const { scrollBody, scrollTo } = embla.dangerouslyGetEngine()
      const distance = add(progress)
      scrollBody.useBaseMass().useBaseSpeed()
      scrollTo.distance(distance, !!snap)
    },
  }
}

// Usage
const { scrollToProgress, scrollByProgress } = createScrollProgressUtils(embla)

scrollToProgress(0.5) // Scroll to progress 0.5
scrollByProgress(0.2) // Scroll 0.2 progress forward
scrollByProgress(-0.2) // Scroll 0.2 progress backward
```
 
### ScrollBy pixels
```js
const createScrollByPx = (embla) => {
  return (px, snap) => {
    const { pxToPercent, scrollTo } = embla.dangerouslyGetEngine()
    const distance = pxToPercent.measure(px) * -1
    scrollTo.distance(distance, !!snap)
  }
}

// Usage
const scrollByPx = createScrollByPx(embla)

scrollByPx(10) // Scroll 10 px forward
scrollByPx(-10) // Scroll 10 px backward
```

Let me know if it helps.

Best,
David

**Comment by EntropyReversed** [comment] 2021-04-14 11:50
Hi @davidcetinkaya!
It is vanilla js-related and this is exactly what I've been looking for!
Thank you very much

**Comment by davidcetinkaya** [comment] 2021-04-14 12:02
Glad to hear that @EntropyReversed. Try it out and let me know if it's working as intended.

Best,
David

**Comment by EntropyReversed** [comment] 2021-04-14 14:14
Have one question. What is n in withinBounds()?

**Comment by davidcetinkaya** [comment] 2021-04-14 14:18
It should be `return distance`. Sorry about that.

**Comment by davidcetinkaya** [comment] 2021-04-14 15:09
@EntropyReversed, it should be `return distance`, not `return n`. Sorry about that. I’ve updated the code snippet.

**Comment by EntropyReversed** [comment] 2021-04-14 16:01
When I call scrollToProgress(-0.5) on the load it scrolls to the middle (as it should), but when I call it from inputs eventListener and I pass its values (that range from 0 to -1) it doesn't work. It goes from start to end by the time input is about 20% scrolled
 ```
input.addEventListener('input', () => {
   let inputValue = input.value / 100;
   scrollToProgress(-inputValue);
   console.log(-inputValue) // this returns numbers from 0 to -1;
})
```

**Comment by davidcetinkaya** [comment] 2021-04-14 16:29
@EntropyReversed I’m not sure why you’re passing a negative number to `scrollToProgress`? It was some time ago I created these methods so if I’m not mistaken you should pass a number from 0 to 1 (positive one).

**Comment by davidcetinkaya** [comment] 2021-04-16 09:55
@EntropyReversed I’m not sure why you’re passing a negative number to `scrollToProgress`? It was some time ago I created these methods but if I’m not mistaken you should pass a **positive** number from 0 to 1.

This is because `scrollToProgress` takes an **absolute** scroll destination. Passing 0.2 will always scroll to the position where the carousel has scrolled 20% of its scrollable length. So a negative value should not be passed to it.

**On a side note**
I added syntax highlighting to your [code snippet](https://github.com/davidcetinkaya/embla-carousel/issues/178#issuecomment-819632098). I hope that's ok.

**Comment by EntropyReversed** [comment] 2021-04-18 19:37
@davidcetinkaya I tried to pass only values from 0 to 1 to scrollToProgress but it doesn't work [here is a codesandbox link](https://codesandbox.io/s/embla-carousel-slide-on-input-u2r86?file=/src/js/index.js). Maybe I'm doing something wrong?

**Comment by davidcetinkaya** [comment] 2021-04-19 09:17
Hi again @EntropyReversed,

I must have rushed through when copy pasting the code snippet. I've created a working [CodeSandbox](https://codesandbox.io/s/embla-carousel-vanilla-github-issue-178-hk61x) for you now. I took the liberty to sync the input when the user scrolls the carousel directly by dragging or clicking the previous and next buttons too. If you don't need it you can just remove that code. 

Sorry for the inconvenience and let me know if it's working now.

Best,
David

**Comment by EntropyReversed** [comment] 2021-04-19 13:37
Hey @davidcetinkaya, it works. And it is more than I asked for but it's everything that I need (i didn't want to bother you with syncing the input when the user scrolls the carousel, was planning to do it myself). So thank you very much and I really appreciate what you did! Btw, love Embla Carousel!

**Comment by davidcetinkaya** [comment] 2021-04-19 13:59
Thanks @EntropyReversed, I’m glad to hear that. Closing this issue as resolved then.

Enjoy!
David

**Closed by davidcetinkaya** 2021-04-19 13:59 UTC
Labels: awaiting response, feature request
