### ISSUE TITLE
TypeErrorCannot read property '0' of undefined

### ISSUE THREAD

**Issue by bitttttten** [davidcetinkaya/embla-carousel#27] opened 2019-10-11 20:52 UTC
Hey! Let me first say, loving the library so far. Very easy to get a really nice carousel with 0 config :) So thanks for the nice defaults.

I just got this error reported in my error tracking, and it leads to `embla-carousel/lib/index`.

```sh
Environment:

Chrome Mobile Version 77.0.3865
Android Version 8.0.0

TypeError: Cannot read property '0' of undefined
 at ./node_modules/embla-carousel/lib/index.js(read:1589:46)
 at ./node_modules/embla-carousel/lib/index.js(apply:1417:29)
 at ./node_modules/logrocket/dist/build.umd.js(HTMLElement.o:2857:31)
```

![chrome_2019-10-11_22-49-17](https://user-images.githubusercontent.com/19930241/66684040-5e5f1b80-ec79-11e9-85e1-569b8daef140.jpg)

So that's

```js
./node_modules/embla-carousel/lib/index.js in read on line 1589:46
1586 | function read(evt, axis) {
1587 | var isMouse = state.isMouse;
1588 | var c = coords[axis];
1589 | var value = isMouse ? evt[c] : evt.touches[0][c];
1590 | return pointValue.setNumber(value);
1591 | }
1592 |  
1593 | function down(evt) {
1594 | state.isMouse = !!evt.type.match(/mouse/);

./node_modules/embla-carousel/lib/index.js in apply on line 1417:29
1413 | var resist = !params.loop && reachedLimit ? 2 : 1;
1414 | target.addNumber(diff / resist);
1415 | evt.preventDefault();
1416 | } else {
1417 | var X = pointer.read(evt, 'x').get();
1418 | var Y = pointer.read(evt, 'y').get();
1419 | var diffX = Math.abs(X - startX.get());
1420 | var diffY = Math.abs(Y - startY.get());
1421 | state.preventScroll = diffX > diffY;
1422 | if (!state.preventScroll && !state.preventClick) up();
```

If you need some copy and paste friendly text.

Not really sure how to go from here! I was going to default value to 0 if evt.touches is not defined although that is just a hack :)

Thanks!

**Comment by davidcetinkaya** [comment] 2019-10-12 00:46
Hi @bitttttten,

Thank you for your kind words and taking time to report this 👍. 
That's strange because I'm assuming your android is a touch device 😕? I don't know if this is a browser specific bug but we should definitely look into this.

I'll let you know as soon as I've released a patch. Thank you for your patience!

Kindly,
David

**Comment by bitttttten** [comment] 2019-10-12 10:05
I can't actually reproduce it myself! Also I don't have an Android 8 device. This error actually came from LogRocket which is like Sentry if you are familiar with that. So it was an error that happened on one of my sites that an error reporter tracked and reported.

I've been asking around for a device running Android 8 so I'll try to reproduce if I get my hands on one 👍

**Comment by davidcetinkaya** [comment] 2019-10-12 11:05
Hello @bitttttten,

Thanks for getting back to me. Interesting, so at the time of writing we can’t rule out that LogRocket is doing something strange 😕.

I’ll apply for [BrowserStack open source testing](https://www.browserstack.com/open-source) as soon as possible.

Let’s see what we can find 👍🏻.

Best,
David

**Comment by davidcetinkaya** [comment] 2019-10-17 12:11
Hi @bitttttten,

**Status update**
I've applied for the BrowserStack open source program and I'm waiting for an approval from their side.

Kindly,
David

**Comment by bitttttten** [comment] 2019-10-17 14:08
Ah good news. Good luck! ✨

**Comment by davidcetinkaya** [comment] 2019-10-18 13:48
Hello again @bitttttten,

**BrowserStack** granted me access today and I tried to reproduce this error for an hour or so without any luck. Do you have any ideas how we can proceed with this? Maybe test ideas?

Thanks in advance.

Best,
David

**Comment by bitttttten** [comment] 2019-10-18 17:53
Hey, good news! congrats ✨ 

ehh sadly not. It's just an anonymous crash report. I tried looking into it myself but it seems weird that the event wasn't there? If it means anything, it was only 1 report out of 1000 users of Android 🤔

**Comment by davidcetinkaya** [comment] 2019-10-19 11:00
Hey @bitttttten, thanks!

Yeah, it's certainly odd. I can't make sense of why the **`event.touches`**  (touch list) is empty on a **`touchstart`** or **`touchmove`** event. I mean that's the whole point of touch events, to track touch pointers 😕. I will close this issue for now. Let's see if someone finds this issue and is able to reproduce it someday. Maybe that person will enlightens us 🙂.

Thank you very much for taking time to open this issue and don't hesitate to do it again if you find a bug or have a feature request.

Cheers!
David

**Comment by korsvanloon** [comment] 2020-02-12 12:29
@davidcetinkaya I still see this error as well on the error reporting of production logs for version 2.6.
For now we've upgraded the package, hope it fixes it (it's indeed hard to reproduce).
However, I think `isMouse` can better be implemented as `evt instanceof MouseEvent` or `isTouch` as `evt instanceof TouchEvent`.

**Comment by davidcetinkaya** [comment] 2020-02-12 12:44
Hello @korsvanloon,

Thank you for your thoughts.

At the time of writing, no fix has been shipped for this issue because I haven't been able to reproduce it. It would be great if we could try to narrow it down. If the `touchmove` event is causing this, setting `isMouse` as you suggest won't help. But if it's the `touchstart` event, the fix you suggest would probably resolve the issue.

Kindly,
David

**Comment by davidcetinkaya** [comment] 2020-02-12 13:12
@bitttttten and @korsvanloon,

I just did some testing and I finally understand why this is happening. If you perform a `touchstart` event and hold the touch for long enough the Android device will actually fire a `mousemove` event, which is interesting. Take a look at the screenshots:

<img width="977" alt="mouse_event" src="https://user-images.githubusercontent.com/11529148/74337562-cf861b00-4da0-11ea-9a92-fa38d3e78b73.png">

<img width="975" alt="mouse_event_details" src="https://user-images.githubusercontent.com/11529148/74337641-f5132480-4da0-11ea-91ee-48d8d1e3d3aa.png">

Embla only checks the **event type** on `pointerdown` (touchstart or mousedown) and this is why Embla fails when a drag interaction that starts with a touch event is suddenly followed by a mouse event.

I'll let you know when I've released a patch version that fixes the issue.

Best,
David

**Comment by korsvanloon** [comment] 2020-02-12 13:26
Great news! Thanks a bunch!

**Comment by bitttttten** [comment] 2020-02-12 13:28
How did you manage to debug that? 🙈 Nice one :)

**Comment by davidcetinkaya** [comment] 2020-02-12 14:09
@korsvanloon and @bitttttten,

I'm happy to announce that patch [version 2.7.4](https://github.com/davidcetinkaya/embla-carousel/releases/tag/v2.7.4) ships with a fix for this issue.

I'd very much **appreciate** if you could take a moment and do some testing so I didn't crash anything else and if you could try to reproduce the issue.

Thanks in advance,
David

**Comment by davidcetinkaya** [comment] 2020-02-17 07:53
Hello guys (@korsvanloon, @bitttttten),

Are you able to verify if the patch release fixes the issue?

Kindly,
David

**Comment by korsvanloon** [comment] 2020-02-17 08:26
Our testing now it seems good, but I'm waiting for the update to go live and see our error reporting for this issue to go down.
I'll come back at you when we've gone live with your update. Should be a couple of days :)

**Comment by davidcetinkaya** [comment] 2020-02-17 11:25
Hi @korsvanloon,
Thank you for the update. Sounds great, looking forward to it 👍.

Best,
David

**Comment by davidcetinkaya** [comment] 2020-03-04 08:59
Hello again @korsvanloon,

I'm going to close this issue due to its stale status. I'd still very much appreciate if you could verify if the patch release fixes the issue for you. It would be great to reach some kind of resolution 🙂.

Kindly,
David

**Closed by davidcetinkaya** 2020-03-04 08:59 UTC
Labels: awaiting feedback, bug, done

**Comment by korsvanloon** [comment] 2020-03-04 09:50
Sorry for the late response but I can confirm this is fixed :)

**Comment by davidcetinkaya** [comment] 2020-03-04 09:53
Thanks @korsvanloon, cheers!
