### ISSUE TITLE
is-selected class no longer added by default

### ISSUE THREAD

**Issue by jodiedoubleday** [davidcetinkaya/embla-carousel#252] opened 2021-12-07 14:22 UTC
### Bug is related to

- [ ] embla-carousel (core package)
- [x] embla-carousel-react
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-docs (documentation website)

### Embla Carousel version

- v6.0.0 + 

### Describe the bug

- is-selected default class is no longer being applied to the embla item.

### CodeSandbox

- [Autplay example](https://codesandbox.io/s/embla-carousel-autoplay-react-2gl44)

### Steps to reproduce

1. Check Console, Is-selected is no longer added to the child element

### Expected behaviour

- Although I have noticed the new class-names plugin - https://www.embla-carousel.com/plugins/class-names/ is i would expect the default class to remain (please correct me if I'm wrong)

### Additional context

- do you have to install the class-names plugin to get the default class name to appear on embla items? I, unfortunately, need that class in order to do a 'fade' effect with CSS

**Comment by davidcetinkaya** [comment] 2021-12-07 15:13
Hello @jodiedoubleday,
 
The **selected class** feature has been removed from the core as of **v.6**. This is stated in the [release details](https://github.com/davidcetinkaya/embla-carousel/releases/tag/v6.0.0). You have to install the [embla-carousel-class-names](https://www.embla-carousel.com/plugins/class-names/) **plugin** in order to "restore" that functionality. You can do it like so:

```js
import ClassNames from 'embla-carousel-class-names'

function MyEmblaCarousel() {
  const [emblaRef, emblaApi] = useEmblaCarousel({ loop: false }, [ClassNames()])
  ...
}
```

Here is the [documentation page](https://www.embla-carousel.com/plugins/class-names/) for the **plugin**.

Cheers,
David

**Comment by davidcetinkaya** [comment] 2021-12-09 12:28
@jodiedoubleday I’m closing this because it’s a duplicate of #239. The solution to this is described [here](https://github.com/davidcetinkaya/embla-carousel/issues/252#issuecomment-988018407).

**Closed** 2021-12-09 12:29 UTC
Labels: demonstration, not a bug

**Comment by Davy-F** [comment] 2022-03-11 09:24
@davidcetinkaya Is there anything that's changed with the way the `is-selected` classes work?
In version 4.20 only one slide would be selected at a given time, and upon selecting a left/right arrow then that would change the class on the new index. However after updating to 6.20 every slide is now initially rendered with an `is-selected` class

**Comment by davidcetinkaya** [comment] 2022-03-11 09:28
@Davy-F, what do you mean by:

- every slide is now initially rendered with an `is-selected` class.

Even slides out of view?
