### ISSUE TITLE
Fade Slider? (again)

### ISSUE THREAD

**Issue by dartess** [davidcetinkaya/embla-carousel#160] opened 2021-03-24 16:50 UTC
### Bug is related to
- [x] The Vanilla JavaScript version
- [ ] The React version
- [ ] Documentation website
- [ ] Other

### Embla Carousel version
- v4.2.0

I've seen similar issues. You have attached this solution these: https://codesandbox.io/s/embla-carousel-github-issue-39-sdkul

Unfortunately it does not work since version 4.2: https://codesandbox.io/s/embla-carousel-github-issue-39-forked-5rxzy

Any ideas how this might work?

**Comment by davidcetinkaya** [comment] 2021-03-24 19:56
Hello @dartess,

Thank you for informing me about this. I've updated the [CodeSandbox](https://github.com/davidcetinkaya/embla-carousel/issues/39#issuecomment-568881867) in the original issue (#39) and it should be working as expected again. Try it out and let me know if it works for you.

I'm closing this as a **duplicate** because I want to keep anything related to setting up a fade slider in the **original issue** (issue #39). It will be easier for anyone looking to implement this to find the information in one place, rather than scattered over many issues. I hope this makes sense. If you have further questions, please continue the discussion in issue #39.

Best,
David

**Comment by davidcetinkaya** [comment] 2021-03-24 19:56
Duplicate of #39.

**Closed by davidcetinkaya** 2021-03-24 19:56 UTC
Labels: bug

**Comment by davidjerleke** [comment] 2024-05-17 10:00
Released in [`8.1.0`](https://github.com/davidjerleke/embla-carousel/releases/tag/v8.1.0).
