### ISSUE TITLE
Broken examples

### ISSUE THREAD

**Issue by magicspon** [davidcetinkaya/embla-carousel#161] opened 2021-03-27 12:56 UTC
### Bug is related to
- [x] The React version

### Embla Carousel version
- v4.3.0

### Describe the bug
The "IOS Picker Default" example is broken. 

### CodeSandbox
https://codesandbox.io/s/embla-carousel-ios-picker-default-react-forked-txgd7?file=/src/js/index.js

### Steps to reproduce
Go to the sandbox, update the dependency to the latest version. Observe

### Expected behavior
https://codesandbox.io/s/embla-carousel-ios-picker-loop-react-6mdkp

### Additional context
Go to the sandbox linked above.
![image](https://user-images.githubusercontent.com/3268717/112721453-bc2e0480-8efb-11eb-9600-8250cc5b7315.png)

**Comment by davidcetinkaya** [comment] 2021-03-27 13:18
Hi Dave (@magicspon),

Thank you for creating this issue. I know why this is happening and will fix it when I have time. The documentation website is using v4.3.0 and I’ve fixed the issue there.

If you want to make it work before I fix it, you have to make sure the slides don’t have position absolute when wheel isn’t ready, an then apply it when it is ready.

I will let you know when I’ve updated the CodeSandbox.

Kindly 
David

**Comment by magicspon** [comment] 2021-03-27 13:38
Aces, thanks for the super speedy response.

**Comment by davidcetinkaya** [comment] 2021-03-27 16:15
Hi again Dave (@magicspon),

I've updated the IOS Picker CodeSandboxes now. Try them out and let me know if they're working as intended now.

Best
David

**Comment by davidcetinkaya** [comment] 2021-03-29 10:48
Hi Dave (@magicspon),

I've updated the IOS Picker CodeSandboxes so I'm closing this issue as resolved. Feel free to open this issue again if you find anything that's not working as expected.

Cheers
David

**Closed by davidcetinkaya** 2021-03-29 10:48 UTC
Labels: awaiting response, bug
