### ISSUE TITLE
Ability to jumpTo (or similar) to slide instead of scrollTo

### ISSUE THREAD

**Issue by simon-mundy** [davidcetinkaya/embla-carousel#176] opened 2021-04-09 05:15 UTC
### Feature request is related to

- [ ] The Vanilla JavaScript version
- [ ] The React version
- [x] The Embla Carousel core (all versions)
- [ ] Documentation website
- [ ] Other

### Is your feature request related to an issue?

- There are situations where I would like to create a Carousel in a modal overlay and jump to a specific slide rather than scrolling/animating to it.

### Describe the solution you'd like

- Could a new set of methods (e.g. `jumpTo` or `select`) be added to allow a non-animated jump to a specific slide.

**Comment by davidcetinkaya** [comment] 2021-04-09 08:00
Hi Simon (@simon-mundy),

Thank you for your feature request. 

> There are situations where I would like to create a Carousel in a modal overlay and jump to a specific slide rather than scrolling/animating to it.

Have you tried using the [startIndex](https://www.embla-carousel.com/api/options/#startindex) **option**? Usage looks like this:

```js
const embla = EmblaCarousel(emblaNode, { startIndex: 2 })
```

You can also make use of the [reInit](https://www.embla-carousel.com/api/methods/#reinit) method like so:

```js
embla.reInit({ startIndex: 2 })
```

If we're to add this feature to the Embla core, I think we need to add it to the following methods:

- [`scrollTo`](https://www.embla-carousel.com/api/methods/#scrollto)
- [`scrollNext`](https://www.embla-carousel.com/api/methods/#scrollnext)
- [`scrollPrev`](https://www.embla-carousel.com/api/methods/#scrollprev)

One way to do it would be to add a `boolean` as a second argument that triggers an `instant` scroll:

```js
embla.scrollTo(2, true)
```

Let me know what you think.

Best,
David

**Comment by davidcetinkaya** [comment] 2021-04-11 18:41
Hello Simon (@simon-mundy),

I've been wanting to add this feature to Embla so I just added it and released [v4.4.0](https://github.com/davidcetinkaya/embla-carousel/releases/tag/v4.4.0), which has this feature. Please try it out and let me know if it's working as intended.

Best,
David

**Comment by simon-mundy** [comment] 2021-04-12 00:15
Amazing! Thankyou @davidcetinkaya will give it a try ASAP

**Comment by davidcetinkaya** [comment] 2021-04-12 07:20
Great @simon-mundy. Let me know if it’s working as intended.

**Comment by davidcetinkaya** [comment] 2021-04-13 08:48
@simon-mundy closing this as resolved. Feel free to open it if you run into any issues.

Best,
David

**Closed by davidcetinkaya** 2021-04-13 08:48 UTC
Labels: feature request, resolved
