### ISSUE TITLE
Enable or disable on certain screen sizes

### ISSUE THREAD

**Issue by flayks** [davidcetinkaya/embla-carousel#99] opened 2020-09-07 19:03 UTC
I'm trying to use Embla (which is fantastic btw, great job) only on mobile, so sort of disabling it on desktop when it's been enabled on mobile (i.e. window resize or orientation change).

So for instance:
1. Load: Desktop screen size (>768) => No carousel
2. Resize: to Mobile (<768) => Init carousel
3. Resize: to Desktop (>768) => Destroy carousel
4. etc…

Flickity has this cool feature where it tracks if a _CSS `after`_ element has a certain content, then enables or disables it with CSS breakpoints. But it's also 51kb of JS, so Embla is def more optimized and lightweight!

Is there any way to have a similar kind of behavior with Embla without having to listen to a window resize event and `embla.destroy()` (which doesn't seem to completely destroy my instances btw) + `embla.reInit(options)` everytime? Or am I missing something?

**Comment by flayks** [comment] 2020-09-07 20:12
Just for the context, this is kind of what I'm trying to achieve, with code based on [this answer](https://github.com/davidcetinkaya/embla-carousel/issues/35#issuecomment-559116920), but it doesn't really seem to work when resizing to a >768 screen size from mobile (it should destroy but the carousel is still "active" and has inline styles applied)

```javascript
import React, { useRef, useEffect, useState } from 'react'
import EmblaCarousel from 'embla-carousel'
import { debounce } from '../utils/functions'


const Carousel = ({ children, settingsProps = '' }) => {
    const carousel = useRef(null)
    let embla = null

    // Settings
    const settings = {
        loop: true,
        ...settingsProps
    }

    // Check for Embla
    const checkEmbla = () => {
        if (window.innerWidth < 768) {
            if (embla === null) {
                embla = EmblaCarousel(carousel.current, settings)
            }
        } else {
            if (embla != null) {
                console.log('destroy')
                embla.destroy()
                embla = null
            }
        }
    }

    useEffect(() => {
        checkEmbla(embla)

        window.addEventListener('resize', () => debounce(checkEmbla(), 100))
    }, [embla])


    return (
        <div className="carousel" ref={carousel}>
            <div className="carousel__items">
                {children}
            </div>
        </div>
    )
}

export default Carousel
```

**Comment by davidcetinkaya** [comment] 2020-09-08 09:04
Hello Félix (@flayks),

Thank you for your question. I think the code in this [old issue you mention](https://github.com/davidcetinkaya/embla-carousel/issues/35#issuecomment-559116920) is probably **outdated**. A lot has changed with the React implementation of Embla Carousel since then.

I took some time to create a [CodeSandbox](https://isr3u.csb.app) that implements what you want to achieve. [Here's the code](https://codesandbox.io/s/embla-carousel-react-github-issue-99-isr3u) if you want to check it out:

```jsx
const EmblaCarousel = ({ children }) => {
  const [emblaRef, emblaApi] = useEmblaCarousel({ loop: false });
  const [emblaIsActive, setEmblaIsActive] = useState(false);

  const initEmblaBelow768px = useCallback(() => {
    const isActive = window.innerWidth < 768;
    setEmblaIsActive(isActive);
  }, [setEmblaIsActive]);

  useEffect(() => {
    initEmblaBelow768px();
    window.addEventListener("resize", initEmblaBelow768px);
    return () => window.removeEventListener("resize", initEmblaBelow768px);
  }, [initEmblaBelow768px]);

  return (
    <div className="embla">
      <div className="embla__viewport" ref={emblaIsActive ? emblaRef : null}>
        <div className="embla__container">
          {/* ...slides */ }
        </div>
      </div>
    </div>
  );
};
```


### So here's what's happening:
- Embla reacts to when its **containerRef** (called emblaRef in the code) changes and won't initialize when it's `null` and if there's an activated instance of Embla it will destroy it automatically.
- So we just skip using the emblaRef by passing `null` when the screen width is >= 768.

### Note
- If this is a part of a bigger project, I would probably create a reusable hook that exposes the window size so other components can make use of it, instead of having it locally in the EmblaCarousel component.
- I would also debounce the resize event with a reusable debounce hook.
- Here's the recommended [bare minimum](https://davidcetinkaya.github.io/embla-carousel/#react-usage) setup for using Embla Carousel with React, if you want to check out the documentation example.

Let me know if it helps!
David

**Comment by flayks** [comment] 2020-09-08 20:34
Thank you so much @davidcetinkaya for your time and answer! That sounds very good. I'll have a look tomorrow and let you know.

**Comment by flayks** [comment] 2020-09-09 06:47
@davidcetinkaya I tried your example and it works… partially, haha. Even on your CodeSandbox, it seems that coming from a small screen (<768, where the carousel is enabled), to the Desktop, the carousel is not really destroyed and we can still drag slides. The behavior should be that when starting on mobile, it should dynamically destroy and reinit the carousel.

**Comment by davidcetinkaya** [comment] 2020-09-09 06:56
@flayks that’s strange. I can’t drag it and it works for me. Which link did you click on?

**Comment by flayks** [comment] 2020-09-09 07:12
This exact one! Here is a video to show more context:
https://streamable.com/8zzx85

**Comment by davidcetinkaya** [comment] 2020-09-09 07:19
So strange. Thanks for the video @flayks. I’ll take a look at it and will let you know when I have something.

**Comment by davidcetinkaya** [comment] 2020-09-09 09:25
Hello again Félix (@flayks),

So I found why this is happening. Embla will re-initialize on the resize event internally, and this resize event is debounced with 500 milliseconds. This is my understanding of it:

- When you resize the window, it triggers Embla's internal debounced resize event.
- When the ref gets `null` Embla destroys itself.
- After 500 milliseconds, the debounced resize callback that was triggered fires and re-initializes Embla.

To solve this I will ship a patch fix as soon as possible. I'll have to make sure the internal re-initialize function doesn't run when the carousel has been destroyed. Nice catch 🙂!

Kindly,
David

**Comment by flayks** [comment] 2020-09-09 10:11
@davidcetinkaya Oh wow, good work on finding that David! I kind of saw when trying the resizing method that it was debounced, but I didn't know that it would affect the destroy method as well.
Thanks for your digging. Other than that, the library is on point 👌

**Comment by davidcetinkaya** [comment] 2020-09-09 13:29
Hi Félix (@flayks),

A patch fix is now on its way, [release v4.0.2](https://github.com/davidcetinkaya/embla-carousel/releases/tag/v4.0.2) should solve this issue. Please give it a go and let me know if it helps.

Best
David

**Comment by flayks** [comment] 2020-09-09 13:35
@davidcetinkaya hella fast! Thanks for fixing that issue, it's gonna help lots on my current project 💥

**Comment by davidcetinkaya** [comment] 2020-09-09 13:35
Hello Félix (@flayks),
[Release 4.0.2](https://github.com/davidcetinkaya/embla-carousel/releases/tag/v4.0.2) comes with a fix for this issue. Please let me know if it's working as intended.

Best,
David

**Comment by davidcetinkaya** [comment] 2020-09-09 15:02
@flayks so this solves the issue right 🙂?

**Comment by flayks** [comment] 2020-09-09 15:03
@davidcetinkaya absolutely! Works like a charm now. Thanks again!

**Comment by davidcetinkaya** [comment] 2020-09-09 15:05
I’m glad to hear that! Thank you for opening this issue and making Embla Carousel better 👍🏻.

Best,
David

**Closed by davidcetinkaya** 2020-09-09 15:05 UTC
Labels: awaiting response, bug, done
