### ISSUE TITLE
The Slider is skipping other items

### ISSUE THREAD

**Issue by leah-cc** [davidcetinkaya/embla-carousel#38] opened 2019-12-13 07:26 UTC
Hello, when users swipe hard enough it looks like its skipping other slides, how can we limit it to only one slide per swipe? `slidesToScroll: 1` doesn't seem to do anything

```javascript
const wrap = document.querySelector('.js-home-slider');
  const viewPort = wrap.querySelector('.js-home-slider-viewport');
  const dots = wrap.querySelector('.js-home-slider-dots');
  const homesliderStart = EmblaCarousel(viewPort, {
    loop: true,
    draggable: true,
    dragFree: false,
    speed: 10,
    startIndex: 0,
    slidesToScroll: 1,
  });
```

**Comment by davidcetinkaya** [comment] 2019-12-15 14:24
Hello @leah-cc,
Thank you for your question.

### The short answer is:
That this is by design and it's intended to work this way.

### The long answer is:
That Embla Carousels animation engine is different from other carousel plugins. It animates by simulating physics in real life and I made this design choice because I wanted a carousel that feels natural to drag and interact with.

Most available carousel plugins only determine which direction the carousel was dragged and then decides whether the carousel should move to the next or the previous slide. If you think about it, this behavior is very unnatural. Because if you were to drag something in real life with a lot of force, it will move further away than if you were to drag it with less force. So Embla not only determines which direction the carousel was dragged, it also measures the drag force. Based on the drag force it will or will not skip slides. It all depends how hard the users drag it.

We have a new browser standard emerging for horisontal scroll areas on websites called CSS scroll snaps, and they also work this way. If you're interested, take a look at this [CSS scroll snap example](https://webkit.org/demos/scroll-snap) and try dragging it on mobile. I decided to go with the same drag design choice for Embla Carousel. I hope I've managed to explain why I made this choice and I hope that all this makes sense to you. 

Kindly,
David

**Comment by gilbertlucas46** [comment] 2019-12-19 06:16
Hi @davidcetinkaya  Thank you for the explanation. But Is there a way to adjust the threshold swipe? Because even with very light swipe it sometimes skip items from 1 - 3 or 1 - 5. Many thanks!

**Comment by davidcetinkaya** [comment] 2019-12-19 08:38
Hello @gilbertlucas46,
Thank you very much for your input on this 👍.

At the time of writing there's no way to control this externally. **If you don't mind**, I'd appreciate if you could share a CodeSandbox or a link that demonstrates the issue you're experiencing. Maybe there's something I'm missing here and a demonstration link may help. Because if it's from 1 - 5 it sounds like Embla may be setup in a way it's not intended to be used.

**If you're interested**, open this [CodeSandbox demonstration](https://2vhrx.csb.app/) in a mobile browser. It's a demonstration where you can compare swipe experience between Embla and CSS Scroll Snaps.

Best,
David

**Comment by gilbertlucas46** [comment] 2019-12-19 11:35
Hello, thank you for your reply. If you try to open your. example on mobile. you can actually see what I mean. https://webm.red/view/wrFu.webm

**Comment by davidcetinkaya** [comment] 2019-12-19 11:49
Hi @gilbertlucas46,

Yes, sorry for being unclear. What I want to convey is that Embla Carousels's drag functionality is designed to work like CSS Scroll Snaps so try swiping in the same manner on the carousel below and they should be very close.
I see that you're using the browser dev tools when swiping. Have you tried this on mobile? Because using the devtools with mouse to simulate touch device input isn't accurate.

**Comment by davidcetinkaya** [comment] 2019-12-29 12:22
I’m closing this issue for now. Feel free to reopen it if you want to discuss it further. Thank you!

**Comment by akardet** [comment] 2020-09-30 16:06
Hi David,

It's me again! You mention exposing an option to configure the friction of the drag force. Is this something that can be explored? 

Thanks,
Sam

**Comment by davidcetinkaya** [comment] 2020-10-01 09:11
Hello again Sam (@akardet),

Thank you for your question. That’s correct. I mentioned that as a suggestion in this issue but didn’t get any response from the issue author. So the discussion basically died and the friction option hasn’t been implemented.

What I had in mind when I mentioned that I could setup a CodeSandbox demonstrating what you want to achieve, was extending Embla with its undocumented method `dangerouslyGetEngine()`. It has been mentioned in issue #86 in [this comment](https://github.com/davidcetinkaya/embla-carousel/issues/86#issuecomment-675434158) an basically is there for the following purposes:

> About the `dangerouslyGetEngine()`, yes it’s not documented but it’s safe to use if you know what you’re doing 🙂. The method basically exposes most of the internal Embla Carousel engine, and is intended to aid plugin authors with maximum extensibility. Another purpose is that it enables for extending the carousel with features that either won’t be added to the core itself, or features that will be released later on.

Are you interested in a solution using this approach?

Kindly,
David

**Comment by akardet** [comment] 2020-10-01 17:23
Ahh I see, yeah it would be helpful to see a CodeSandbox example if it's not too much trouble. 

Thanks,
Sam

**Comment by davidcetinkaya** [comment] 2020-10-07 17:58
Hello Sam (@akardet),

As you mentioned in our previous conversation you’re aware of the design choice with momentum scrolling. If you still want to use Embla but change that behavior I don’t mind trying to achieve this and create a CodeSandbox for you, like I suggested [here](https://github.com/davidcetinkaya/embla-carousel/issues/38#issuecomment-702000996).

I want to mention that I’ve not been able to work on this project for a period now and I’m hoping to be able to spend some time on it soon. But at the time of writing I don’t know when that will be possible.

Kindly,
David

**Comment by davidcetinkaya** [comment] 2021-03-30 12:36
For anyone interested (@leah-cc, @gilbertlucas46), is this close to the desired behavior you would like to see?

https://user-images.githubusercontent.com/11529148/112989433-3614f680-9165-11eb-957e-72721cd287f5.mp4

Kindly,
David

**Comment by davidcetinkaya** [comment] 2021-03-30 12:38
For anyone interested, maybe (@leah-cc, @gilbertlucas46, @farshidshahmoradi1996), is this close to the desired behavior you would like to see?

https://user-images.githubusercontent.com/11529148/112989433-3614f680-9165-11eb-957e-72721cd287f5.mp4

Kindly,
David

**Comment by davidcetinkaya** [comment] 2021-03-30 16:49
For anyone interested, maybe (@leah-cc, @gilbertlucas46, @farshidshahmoradi1996, @akardet), is this close to the desired behavior you would like to see?

https://user-images.githubusercontent.com/11529148/112989433-3614f680-9165-11eb-957e-72721cd287f5.mp4

Kindly,
David

**Comment by jeiea** [comment] 2021-04-05 05:02
@davidcetinkaya Watching at the clip, I expect threshold for scroll to be decreased. But maybe that will be problem of parameter.
I'll be satisfied with `dangerouslyGetEngine()` way if you don't want to expose public API for this. Could you provide any hint for this?

**Comment by davidcetinkaya** [comment] 2021-04-05 11:14
Hi @jeiea,

> I expect threshold for scroll to be decreased

I'm not following. How do you mean?

> I'll be satisfied with `dangerouslyGetEngine()` way if you don't want to expose public API for this.

It seems like a lot of people want this so I think I'm going to release this publicly, but I can't give an ETA for it. Recently, I've had a little time to look over some parts of the code that can be simplified so it will be possible to add this feature without adding to the current bundle size.

Best,
David

**Comment by jeiea** [comment] 2021-04-05 12:21
I think required drag distance to swipe is too long. That maybe due to wide width but it can be shortened. And even if drag distance is short, I will admit it as swipe if speed is fast enough. Because it would be matter of parameter, it's consistent with my expectation overall.

**Comment by davidcetinkaya** [comment] 2021-04-05 12:28
@jeiea, the required drag distance may look like it's long in the video, but it actually isn't.

**Comment by jeiea** [comment] 2021-04-05 12:33
I expected all swipe cause scroll. But it didn't. What makes difference?

**Comment by davidcetinkaya** [comment] 2021-04-05 12:34
@jeiea I'm just moving the mouse before I actually start dragging (performing a pointerdown and pointerup).

**Comment by davidcetinkaya** [comment] 2021-04-05 14:33
@jeiea The bottom line is, you can’t see where I release the mouse after dragging on the video, so you can’t tell how far I’ve dragged the carousel with the mouse before releasing the mouse button. This is because there’s nothing that visually indicates this. I’m not using a grab cursor when the mouse button is down for example.

> I think required drag distance to swipe is too long

So your assumption about drag distance is probably not accurate in this case.

**Comment by jeiea** [comment] 2021-04-05 14:46
Ah, I had a illusion that 2, 3, 5th swipes failed to scroll to the next slides. Perhaps reverse elasticity give me that illusion.

**Comment by davidcetinkaya** [comment] 2021-04-05 14:51
@jeiea ah I see. Your comment makes sense now. Every drag move succeeds in the video.  It’s just that the 1st and the 4th drag is with less force so it doesn’t bounce back. As you realized, it’s reversed elasticity 👍🏻.

**Comment by davidcetinkaya** [comment] 2021-04-18 11:28
@jeiea I have a working draft of this feature now. Care to try it out? If yes, please tell me if you prefer a VanillaJs or ReactJs CodeSandbox setup.

Best,
David

**Comment by jeiea** [comment] 2021-04-18 11:36
I prefer react one.

**Comment by davidcetinkaya** [comment] 2021-04-18 11:38
@jeiea thank you for your swift response. I'll let you know when it's ready.

**Comment by davidcetinkaya** [comment] 2021-04-18 11:48
@jeiea here are the links:

- [React CodeSandbox](https://codesandbox.io/s/embla-carousel-react-github-issue-38-3yoit).
- [React App View](https://3yoit.csb.app/) (that simulates a real browser environment).

The new **option** is called `skipSnaps`. When it's set to `false`, it will enable the described behavior in this issue. Let me know how it goes.

**Comment by jeiea** [comment] 2021-04-21 02:51
@davidcetinkaya Sorry for late reply. I showed it to my team, and it seems good.

**Comment by davidcetinkaya** [comment] 2021-04-21 10:13
@jeiea thanks for taking time to test this. I'll release this as soon as I get the chance with **v4.5.0**. Note that you need to set your options to `skipSnaps: false` to enable this.

In the next major version (which will be **5.0.0**), this will be the default behavior though.

**Comment by jeiea** [comment] 2021-04-21 10:30
I just applied to real project and found some strange behavior. It seems when `loop: true` both ends of container are not regarded as snaps. Could you check it?

**Comment by davidcetinkaya** [comment] 2021-04-21 10:34
@jeiea sorry, I forgot to change the CodeSandbox code to the latest. I solved this issue yesterday. Try the CodeSandbox [here](https://github.com/davidcetinkaya/embla-carousel/issues/38#issuecomment-821979093) again and let me know if we're talking about the same issue.

**Comment by jeiea** [comment] 2021-04-21 10:42
I confirmed that it is the same issue. Thank you.

**Closed** 2021-04-22 12:50 UTC
Labels: feature request, upcoming

**Comment by davidcetinkaya** [comment] 2021-04-22 13:09
@jeiea this feature has been released with [v4.5.0](https://github.com/davidcetinkaya/embla-carousel/releases/tag/v4.5.0). 

Enjoy,
David

**Comment by jeiea** [comment] 2021-04-22 18:06
It's nitpicking but the read more link in release description linked to localhost.

**Comment by davidcetinkaya** [comment] 2021-04-22 18:11
Thank you @jeiea. That link is important so it's not nitpicking 👍.

**Comment by akardet** [comment] 2021-04-22 22:45
Just added the new option to my app and it's working flawlessly! Thanks for the great work, David 😊
