### ISSUE TITLE
Passive listener violation in chrome and other browsers

### ISSUE THREAD

**Issue by searchableguy** [davidcetinkaya/embla-carousel#288] opened 2022-02-23 16:55 UTC
### Bug is related to

- [X] embla-carousel (core package)
- [ ] embla-carousel-react
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-docs (documentation website)

### Embla Carousel version

- Latest

### Describe the bug

Chrome and other browsers shipped a feature for even listeners to improve scrolling experience. As a result, they also started warning in console about the violation. 

https://chromestatus.com/feature/5745543795965952

All browsers now support passive so the fix should be to simply enable it to the event listeners we are attaching. I can try to open a PR for this.

### CodeSandbox

- Open https://www.embla-carousel.com/examples/basic/
- Open dev tools and go to console to see the warning.
- 
![image](https://user-images.githubusercontent.com/73341821/155367500-f0ac3f9a-e86d-41b4-ba79-6cc10ee2c28a.png)

### Expected behavior

- Event listeners should be passive.

### Additional context

That said, I've not dug much into this so I might be unaware of any intentional context behind not using passive listeners here.

**Comment by davidcetinkaya** [comment] 2022-02-23 17:38
Hello @searchableguy,

Thanks for your issue. I appreciate the effort to report this in order to improve this library.

A friendly reminder: Please take a moment to search existing issues before creating a new one. 

- Here’s [what I think](https://github.com/davidcetinkaya/embla-carousel/issues/62#issuecomment-628569509) about passive listeners for Embla.
- And please [read this](https://github.com/davidcetinkaya/embla-carousel/issues/62#issuecomment-636436803) too.

If your carousel isn’t above the fold, you can lazy load it and Google won’t bash on you.

- #62
- #235

Best,
David

**Comment by davidcetinkaya** [comment] 2022-02-23 17:39
Duplicate of #62.

**Closed by davidcetinkaya** 2022-02-23 17:39 UTC
Labels: bug

**Comment by searchableguy** [comment] 2022-02-23 17:42
Thanks for the response. I apologize for the duplicate. I actually did search for existing issues but used the wrong keyword "violation error".

I understand the stance and thanks for the workaround.

**Comment by davidcetinkaya** [comment] 2022-02-23 18:49
@searchableguy no worries. Was just a reminder in case you hadn’t 🙂. If you happen to know a solution that uses passive listeners and still makes it possible to lock the intersecting scroll., please share.

Cheers,
David

**Comment by davidjerleke** [comment] 2023-01-20 19:47
@searchableguy this feature has been released with [v7.0.7](https://github.com/davidjerleke/embla-carousel/releases/tag/v7.0.7).
