### ISSUE TITLE
Missing plugins parameter for reInit method

### ISSUE THREAD

**Issue by TomOne** [davidcetinkaya/embla-carousel#238] opened 2021-11-08 13:37 UTC
### Bug is related to

- [x] The Embla Carousel core (all versions)

### Embla Carousel version

- v6.0.0

### Describe the bug

According to https://www.embla-carousel.com/api/methods/#reinit, `reInit` allows second parameter for the plugins, but the code is currently missing this parameter: https://github.com/davidcetinkaya/embla-carousel/blob/4618bc1875df6dda2d1a0494ef3661231ad62530/packages/embla-carousel/src/components/index.ts#L36

### CodeSandbox

None required

### Steps to reproduce

1. Attempt to pass plugins to the `reInit` method in addition to `options`.
2. See the TypeScript error `Expected 0-1 arguments, but got 2.`

### Expected behavior

The types for the `reInit` method should match the docs.

### Additional context

None

**Comment by davidcetinkaya** [comment] 2021-11-08 14:17
Nice catch. Thanks @TomOne.

The generic type that extends the plugin base type is also missing.

I’ll look into this when I get the chance.

Best,
David

**Comment by davidcetinkaya** [comment] 2021-11-09 07:06
Hello @TomOne,

I've just [released v6.0.1](https://github.com/davidcetinkaya/embla-carousel/releases/tag/v6.0.1) with a patch fix for this bug. Thank you for creating this bug report and let me know if it works as intended now.

Best,
David

**Comment by TomOne** [comment] 2021-11-09 08:43
@davidcetinkaya, works perfectly now. Thanks for the fix.

**Closed** 2021-11-09 08:56 UTC
Labels: bug, resolved, typescript

**Comment by davidcetinkaya** [comment] 2021-11-14 12:32
Cheers @TomOne 👍🏻.
